// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebAppService.DAL;

#nullable disable

namespace VehicleWebAppService.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20220107113410_changedIdNamesForEntities")]
    partial class changedIdNamesForEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeId"), 1L, 1);

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeId");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            VehicleMakeId = 1,
                            Abrv = "BMW",
                            Name = "BMW"
                        },
                        new
                        {
                            VehicleMakeId = 2,
                            Abrv = "Ford",
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeId = 3,
                            Abrv = "Audi",
                            Name = "Audi"
                        },
                        new
                        {
                            VehicleMakeId = 4,
                            Abrv = "Porsche",
                            Name = "Porsche"
                        },
                        new
                        {
                            VehicleMakeId = 5,
                            Abrv = "Fiat",
                            Name = "Fiat"
                        },
                        new
                        {
                            VehicleMakeId = 6,
                            Abrv = "BMW",
                            Name = "BMW"
                        },
                        new
                        {
                            VehicleMakeId = 7,
                            Abrv = "VW",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            VehicleMakeId = 8,
                            Abrv = "VW",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            VehicleMakeId = 9,
                            Abrv = "Opel",
                            Name = "Opel"
                        },
                        new
                        {
                            VehicleMakeId = 10,
                            Abrv = "GM",
                            Name = "General Motors"
                        });
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"), 1L, 1);

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebAppService.Models.VehicleMake", "VehicleMake")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
