// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebAppService.DAL;

#nullable disable

namespace VehicleWebAppService.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleMakeId"), 1L, 1);

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeId");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            VehicleMakeId = 1,
                            Abrv = "BMW",
                            Name = "Bayerische Motoren Werke AG"
                        },
                        new
                        {
                            VehicleMakeId = 2,
                            Abrv = "Ford",
                            Name = "Ford Motor Company"
                        },
                        new
                        {
                            VehicleMakeId = 3,
                            Abrv = "Audi",
                            Name = "Audi AG"
                        },
                        new
                        {
                            VehicleMakeId = 4,
                            Abrv = "Fiat",
                            Name = "Fiat S.p.A."
                        },
                        new
                        {
                            VehicleMakeId = 5,
                            Abrv = "VW",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            VehicleMakeId = 6,
                            Abrv = "Opel",
                            Name = "Opel Automobile GmbH"
                        },
                        new
                        {
                            VehicleMakeId = 7,
                            Abrv = "GM",
                            Name = "General Motors"
                        },
                        new
                        {
                            VehicleMakeId = 8,
                            Abrv = "Hyundai",
                            Name = "Hyundai Motor Company"
                        },
                        new
                        {
                            VehicleMakeId = 9,
                            Abrv = "Honda",
                            Name = "Honda Motor Company"
                        },
                        new
                        {
                            VehicleMakeId = 10,
                            Abrv = "Toyota",
                            Name = "Toyota Motor Corporation"
                        },
                        new
                        {
                            VehicleMakeId = 11,
                            Abrv = "Mercedes",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            VehicleMakeId = 12,
                            Abrv = "Peugeot",
                            Name = "Peugeot S.A."
                        });
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleModelId"), 1L, 1);

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebAppService.Models.VehicleMake", "VehicleMake")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleMake");
                });

            modelBuilder.Entity("VehicleWebAppService.Models.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
